version: '3.8'
services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: community_events
    ports:
      - "3306:3306"
    networks:
      - mynetwork

  flask:
    build: .
    container_name: flask-container
    depends_on:
      - mysql
    ports:
      - "5000:5000"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge